// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

List<CameraInfo> availableCameras() =>
    RustLib.instance.api.crateApiSimpleAvailableCameras();

void startScan({
  required RustStreamSink<List<BarcodeResult>> resultSink,
  required RustStreamSink<Frame> frameSink,
  required int index,
}) => RustLib.instance.api.crateApiSimpleStartScan(
  resultSink: resultSink,
  frameSink: frameSink,
  index: index,
);

List<BarcodeResult> analyzeImage({required String path}) =>
    RustLib.instance.api.crateApiSimpleAnalyzeImage(path: path);

List<BarcodeResult> analyzeBytes({
  required List<int> bytes,
  required int width,
  required int height,
  required String format,
}) => RustLib.instance.api.crateApiSimpleAnalyzeBytes(
  bytes: bytes,
  width: width,
  height: height,
  format: format,
);

class BarcodeResult {
  final String text;
  final Uint8List bytes;
  final String format;
  final Point topLeft;
  final Point topRight;
  final Point bottomRight;
  final Point bottomLeft;

  const BarcodeResult({
    required this.text,
    required this.bytes,
    required this.format,
    required this.topLeft,
    required this.topRight,
    required this.bottomRight,
    required this.bottomLeft,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      bytes.hashCode ^
      format.hashCode ^
      topLeft.hashCode ^
      topRight.hashCode ^
      bottomRight.hashCode ^
      bottomLeft.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BarcodeResult &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          bytes == other.bytes &&
          format == other.format &&
          topLeft == other.topLeft &&
          topRight == other.topRight &&
          bottomRight == other.bottomRight &&
          bottomLeft == other.bottomLeft;
}

class CameraInfo {
  final int index;
  final String name;

  const CameraInfo({required this.index, required this.name});

  @override
  int get hashCode => index.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CameraInfo &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          name == other.name;
}

class Frame {
  final Uint8List bytes;
  final int width;
  final int height;

  const Frame({required this.bytes, required this.width, required this.height});

  @override
  int get hashCode => bytes.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Frame &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          width == other.width &&
          height == other.height;
}

class Point {
  final int x;
  final int y;

  const Point({required this.x, required this.y});

  @override
  int get hashCode => x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Point &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y;
}
